### ISSUE TITLE
ExperimentalWarning: The fs.promises API is experimental

### ISSUE THREAD

**Issue by kriskate** [googleapis/nodejs-logging-winston#105]
#### Environment details

  - OS: macOS High Sierra
  - Node.js version: 10.1.0
  - npm version: 5.6.0
  - `@google-cloud/logging-winston` version: 0.9.0

#### Steps to reproduce

``` import { LoggingWinston } from'@google-cloud/logging-winston' ```

I receive the console error
```(node:27103) ExperimentalWarning: The fs.promises API is experimental```
which is unfortunate because I'm redirecting the console to the logger and always get this error in Stackdriver as well

**Comment by ofrobots** [comment]
Hi @kriskate! Thanks for the bug report. Given that you're using ES6 modules can you also provide details on how you are using them? E.g. are you using babel or TypeScript, and if so, what versions.

Secondly can you run with the Node.js `--trace-warnings` flag so that we can see the stack trace leading to the warning? `node --trace-warnings index.js`.

**Comment by kriskate** [comment]
Hey, thanks for the prompt response.
requiring the modules has the same result
```let LoggingWinston = require('@google-cloud/logging-winston')```

```
(node:33405) ExperimentalWarning: The fs.promises API is experimental
    at Object.get [as promises] (fs.js:84:15)
    at __importStar (~/node_modules/google-auth-library/build/src/auth/googleauth.js:58:96)
    at Object.<anonymous> (~/node_modules/google-auth-library/build/src/auth/googleauth.js:65:10)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
```

**Comment by ofrobots** [comment]
Thanks! I believe this is an issue in the [google-auth-library module](https://npm.im/google-auth-library) so I am going to move the issue there.

**Comment by ofrobots** [comment]
This issue was moved to google/google-auth-library-nodejs#392
