### ISSUE TITLE
Winston 3 - Getting 'Unknown log level: info' 

### ISSUE THREAD

**Issue by frandiox** [googleapis/nodejs-logging-winston#184]
Hi! I'm updating to Winston@3 and I'm now getting `Unknown log level: info` with minimal code.

It happens because I'm using `colorize` format so when checking if `info` (or any other) keyword [is a property of the levels map](https://github.com/googleapis/nodejs-logging-winston/blob/master/src/common.ts#L112), it fails since it's not a plain `info` string but a colorized `info` string.

Before, it was working because the `colorize` setting was passed directly to the `Console` transport, but I think in winston@3 we need to pass it to the logger as a format and thus affects every transport.

**Edit:** Looks like there's a way to set format to specific transports but it's not documented: https://github.com/winstonjs/winston/issues/1401

**Comment by ofrobots** [comment]
Hi @frandiox. It seems that you found the solution through winstonjs/winston#1401. I take it that this issue can be closed. If this is a mistake, please leave a comment and we can reopen this.

**Comment by govindrai** [comment]
This is still a problem: I'm getting a  

```
/srv/node_modules/winston/lib/winston/logger.js:307
2019-05-14 21:40:20 dlq[20190514t141538]        throw ex;
2019-05-14 21:40:20 dlq[20190514t141538]        ^
2019-05-14 21:40:20 dlq[20190514t141538]
2019-05-14 21:40:21 dlq[20190514t141538]  Error: Unknown log level: error      at LoggingCommon.log (/srv/node_modules/@google-cloud/logging-winston/build/src/common.js:86:19)      at LoggingWinston.log (/srv/node_modules/@google-cloud/logging-winston/build/src/winston3.js:44:21)      at ExceptionStream._write (/srv/node_modules/winston/lib/winston/exception-stream.js:48:29)      at doWrite (/srv/node_modules/winston/node_modules/readable-stream/lib/_stream_writable.js:405:139)      at writeOrBuffer (/srv/node_modules/winston/node_modules/readable-stream/lib/_stream_writable.js:394:5)      at ExceptionStream.Writable.write (/srv/node_modules/winston/node_modules/readable-stream/lib/_stream_writable.js:303:11)      at DerivedLogger.ondata (/srv/node_modules/winston/node_modules/readable-stream/lib/_stream_readable.js:662:20)      at DerivedLogger.emit (events.js:194:15)      at addChunk (/srv/node_modules/winston/node_modules/readable-stream/lib/_stream_readable.js:297:12)      at readableAddChunk (/srv/node_modules/winston/node_modules/readable-stream/lib/_stream_readable.js:279:11)
```
the GCP Winston transport should be able to handle formats being passed down from the logger.

Here's my logger setup:


```
const {createLogger, transports, format} = require("winston");
const config = require("./config");

const consoleTransport = new transports.Console();

const logger = new createLogger({
    // TODO: would be great if this feature could have a switch
    level: config.maxLogLevel || 'debug',
    format: format.combine(
      format.colorize(),
      format.simple()
    ),
    transports: [
      consoleTransport
    ],
    exceptionHandlrsers: [consoleTransport],
    exitOnError: false
})

if (config.environment === 'Staging' || config.environment === 'Production') {
    const {LoggingWinston} = require('@google-cloud/logging-winston');
    const stackDriverTransport = new LoggingWinston({
    });
    logger.add(stackDriverTransport)
    logger.exceptions.handle(stackDriverTransport)
}
```

**Comment by ofrobots** [comment]
Ack. This is a problem in this transport. Self-assigning.
