### ISSUE TITLE
Question: how to debug the logger itself

### ISSUE THREAD

**Issue by polymorph-andrel** [googleapis/nodejs-logging-winston#272]
Hi everyone

I have configured Winston to use this Stackdriver transport according to the documentation, but it doesn't appear to work. The reason I say this is because I can see the console logging, but nothing on Stackdriver. Is there a way to enable additional diagnostic output of the logger itself to help me diagnose the problem?

Thanks in advance for any help, much appreciated.

**Comment by DominicKramer** [comment]
Thanks for reaching out.  There is not a log level setting for the logger itself where the logger will print what it is doing to give insight.  However, for problems I have seen communicating to the API, for authentication problems, or other such problems an error is printed to the console.  If you are running in the cloud, console output is collected and will appear in the Logs Viewer.

If you are not seeing such an error message, my next suggestion would be to explicitly state what project you want the logs to be logged to.  If you have multiple projects, perhaps the logs are going to project you are not expecting.This is done when configuring the logger,
```js
const winston = require('winston');
const {LoggingWinston} = require('@google-cloud/logging-winston');

const loggingWinston = new LoggingWinston({
    projectId: 'my-project'
});

const logger = winston.createLogger({
  level: 'info',
  transports: [
    new winston.transports.Console(),
    // Add Stackdriver Logging
    loggingWinston,
  ]
});

logger.error('some error');
```
If that doesn't work, could you please provide a repro (including whether it is Winston 2 or 3) that we can look into to help you out and see if there is a bug in the logging winston library itself.  Thanks.

**Comment by polymorph-andrel** [comment]
Hi Dominic

Thanks for the fast, friendly and detailed response. Much appreciated.

I'll try that quickly and get back to you.

**Comment by polymorph-andrel** [comment]
Ok, so I'll include some additional details seeing as I am still not getting any joy:

The project is a typescript Node.js graphQL API. This is the logger we're using:

```javascript
import { createLogger, format, transports, LeveledLogMethod, Logger } from 'winston'
import fss from 'fast-safe-stringify'
import { LoggingWinston } from '@google-cloud/logging-winston';

const loggingWinston = new LoggingWinston({
  projectId: 'ep-ei-blimp-main'
});

const logger = (logLevel: string, namespace: string) => {
  return createLogger({
    level: logLevel,
    format: format.combine(
      format.label({ label: namespace }),
      format.json(),
      format.timestamp({ alias: 'ts' }),
      format.printf(info => `${info.ts} [${info.label}] ${info.level}: ${fss(info.message)}`)
    ),
    transports: [
      new transports.Console(),
      loggingWinston,
    ]
  })
}

export { LeveledLogMethod, Logger }
export default logger
```

It is running on a PM2-based image on a Container Optimized Compute Engine on Google Cloud. The compute engine service account has the API access scope and Log Writer role.

Inspecting the log output with:

`docker exec -it [[container-name]] pm2 logs 0`

gives me:

`[TAILING] Tailing last 15 lines for [0] process (change the value with --lines option)
/root/.pm2/logs/BlimpApi-error-0.log last 15 lines:
/root/.pm2/logs/BlimpApi-out-0.log last 15 lines:
0|BlimpApi | 2019-03-07T19:24:32.303Z [blimp-api] info: {"env":{"MONGODB_URL":"mongodb://localhost:27017/blimp","LOG_LEVEL":"debug"}}
0|BlimpApi | 🚀 Server ready at http://localhost:4000/graphql
0|BlimpApi | 2019-03-07T19:24:32.610Z [blimp-api] debug: {"rej":{"name":"MongoNetworkError","errorLabels":["TransientTransactionError"]}}
0|BlimpApi | 2019-03-07T19:24:32.618Z [blimp-api] error: "Error connecting to database: MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]"`

The output above is what is captured by PM2. It is very likely PM2 is somehow causing this problem, but the log doesn't even suggest what might be wrong.

**Comment by DominicKramer** [comment]
Sorry for the late reply.  At first glance since the logs don't have any errors authenticating with Google Cloud, I suspect that perhaps our library isn't working with PM2 for some reason.  The next action will will take is to try to replicate what you are seeing using PM2.

**Comment by DominicKramer** [comment]
I'm having trouble pinpointing what the cause of your issue could be.  I've used your code to test `pm2` and `logging` integration locally, and I'm correctly able to see logs appear in Stackdriver logging (under the global resource).

I'm now looking into whether there is an interaction on GCE that could be causing this.  Are you still seeing this issue, and is it only on Container Optimized Compute Engine?

Another thing that I just thought of is that perhaps your logs are appearing under the wrong resource group in Stackdriver logging.  That is, perhaps they are under global instead of "GCE VM Instance".

If you notice that is the case, let me know as it would be a bug in `@google-cloud/logging`.  Thanks for your help in tracking this issue down.

**Comment by DominicKramer** [comment]
I've been able to reproduce what you are seeing and have verified that it is an issue with `@google-cloud/logging` itself.

In particular, consider the following `index.ts` file:
```js

import * as express from 'express';

// Imports the Google Cloud client library
const {Logging} = require('@google-cloud/logging');

// Your Google Cloud Platform project ID
const projectId = 'my-project-id';

// Creates a client
const logging = new Logging({
  projectId: projectId,
});

const app = express();

function log(text: string) {
  // The name of the log to write to
  const logName = 'my-log';
  // Selects the log to write to
  const log = logging.log(logName);

  // The metadata associated with the entry
  const metadata = {resource: {type: 'gce_instance'}};
  // Prepares a log entry
  const entry = log.entry(metadata, text);

  // Writes the log entry
  log
    .write(entry)
    .then(() => {
      console.log(`Logged: ${text}`);
    })
    .catch((err: Error) => {
      console.error('ERROR:', err);
    });
}

app.get('/', (req, res) => {
  const ts = Date.now();
  const text = 'Hello, world! at ' + ts;
  log(text);
  res.send('Logging at ' + ts);
});

const port = process.env.PORT || 80;
app.listen(port, () => {
  log('Listening on port ' + port);
  console.log('Listenting on port ' + port);
});

log('Some custom message');
```
With the Logging API enabled and running the code locally, I see the logs correctly appear under the "GCE VM Instance resource" in the logs viewer.

However, if I create a Docker image that runs the above app (using node and not pm2), create a GCE instance based on that image using the Container Optimized OS, select "Allow full access to all Cloud APIs", use the default Compute Engine service account, Allow HTTP traffic, and Enable Stackdriver Logging, when I launch the VM, the logs do not appear under any resource in the logging console.

If I ssh into the instance and run `docker logs <id of running container>` I see that the following error occurred:
```
ERROR: { Error: 7 PERMISSION_DENIED: The caller does not have permission
    at Object.exports.createStatusError (/app/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/app/node_modules/grpc/src/client_interceptors.js:1204:28)
    at InterceptingListener._callNext (/app/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/app/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/app/node_modules/grpc/src/client_interceptors.js:845:24)
  code: 7,
  metadata: Metadata { _internal_repr: {} },
  details: 'The caller does not have permission',
  note:
   'Exception occurred in retry method that was not classified as transient' }
```

As such, I am going to move this issue to the `@google-cloud/logging` repo.
