### ISSUE TITLE
Logging stops after gax timeout

### ISSUE THREAD

**Issue by ralphkocher** [googleapis/nodejs-logging-winston#406]
#### Environment details
-
  - OS: Alpine latest: 3.9.4
  - Node.js version: 12.12.0
  - `@google-cloud/logging-winston` version: 2.1.0

#### Steps to reproduce

After using latest nodejs-logging-winston in 2.1.0 the logging to Stackdriver stops suddenly after a few hours of logging. A few minutes before it stops we see the following exception trace coming from google-gax:

`Error: Retry total timeout exceeded before any response was received
    at repeat (/app/node_modules/google-gax/build/src/normalCalls/retries.js:80:31)
    at Timeout._onTimeout (/app/node_modules/google-gax/build/src/normalCalls/retries.js:113:25)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)`

After switching back to nodejs-logging-winston version 2.0.1 everything worked fine again. The google-gax message does not appear in 2.0.1 but immediately  comes back if we switch forward to version 2.1.0

Any ideas?

**Comment by DominicKramer** [comment]
Thank you for your feedback.  This doesn't look like it is specific to winston integration.  Further, between `nodejs-logging-winston` vesion 2.0.1 and 2.1.0 an update of `@google-cloud/logging` from `5.1.0` to `5.3.1` was done.  I suspect this issue is in `@google-cloud/logging` itself, and so I'm moving this issue there.
