### ISSUE TITLE
Could not load the default credentials

### ISSUE THREAD

**Issue by krzysztof-o** [googleapis/nodejs-logging-winston#566]
Hello,
I started using winston transport on GKE and 2/3 pods work just fine but 3rd pod returns this during initialisation:
```
Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.
    at GoogleAuth.getApplicationDefaultAsync (/usr/src/avatarux/games/node_modules/google-auth-library/build/src/auth/googleauth.js:173:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at GoogleAuth.getClient (/usr/src/avatarux/games/node_modules/google-auth-library/build/src/auth/googleauth.js:545:17)
    at GrpcClient._getCredentials (/usr/src/avatarux/games/node_modules/google-gax/src/grpc.ts:160:20)
    at GrpcClient.createStub (/usr/src/avatarux/games/node_modules/google-gax/src/grpc.ts:332:19)
```

I am using standard code from the provided example without passing projectId and keyFile. I looked for similar issues but all seem to be closed without fixing the actual root cause.

**Comment by nicoleczhu** [comment]
Hi, can you share your code snippet? Which example are you referring to?

I think the other closed issues were referring to Cloud Functions. 

When you exec into your failed pod, what does `gcloud auth list` say?

**Comment by nicoleczhu** [comment]
Closing this ticket for now, as the issue doesn't originate from this repo and there are no action items here.

**Comment by austonpramodh** [comment]
Hi,
I am facing a kind of similar issue.
*Logs:*
```
(node:24) UnhandledPromiseRejectionWarning: Error: 7 PERMISSION_DENIED: The caller does not have permission
    at Object.callErrorFromStatus (/app/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client.js:176:52)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)
    at /app/node_modules/@grpc/grpc-js/build/src/call-stream.js:145:78
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
(node:24) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 11)
```

Initially, I thought the pod doesn't have permissions. I tried running the curl metadata server inside pod and I got following response:
```
/app # curl http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/scopes -H "Metadata-Flavor:Google"
https://www.googleapis.com/auth/devstorage.read_only
https://www.googleapis.com/auth/logging.write
https://www.googleapis.com/auth/monitoring
https://www.googleapis.com/auth/servicecontrol
https://www.googleapis.com/auth/service.management.readonly
https://www.googleapis.com/auth/trace.append
```

I am unable to find a solution, please help.
