### ISSUE TITLE
Using LoggingWinston object with no project id causes nodejs to crash in node >16

### ISSUE THREAD

**Issue by eamonnmcevoy** [googleapis/nodejs-logging-winston#623]
1) Is this a client library issue or a product issue?
I'm not sure, but this might be an issue with https://github.com/googleapis/nodejs-common. I encountered it using this package.

2) Did someone already solve this?
no

3) Do you have a support contract?
no

#### Environment details

  - OS: tested on macos big sur (intel) and nodejs-16-alpine docker container on google cloud run
  - Node.js version: 16 and above
  - npm version: 7.21.0
  - `@google-cloud/logging-winston` version: 4.1.0

#### Steps to reproduce

  1. Run the following sample
 
```js
const express = require('express')
const winston = require('winston');
const {LoggingWinston} = require('@google-cloud/logging-winston');
const app = express()
const port = 3000

const loggingWinston = new LoggingWinston();
const logger = winston.createLogger({
  level: 'info',
  transports: [
    new winston.transports.Console(),
    loggingWinston,
  ],
});


app.get('/', (req, res) => {
  logger.info('get');
  res.send('Hello World!')
})

app.listen(port, () => {
  console.log(`Example app listening at http://localhost:${port}`)
})
```

  2. make a GET request
  3. after a short delay the app will crash

```js
/Users/eamonnmcevoy/gcloud-try-catch/node_modules/google-auth-library/build/src/auth/googleauth.js:95
                        throw new Error('Unable to detect a Project Id in the current environment. \n' +
                              ^

Error: Unable to detect a Project Id in the current environment. 
To learn more about authentication and Google APIs, visit: 
https://cloud.google.com/docs/authentication/getting-started
    at /Users/eamonnmcevoy//gcloud-try-catch/node_modules/google-auth-library/build/src/auth/googleauth.js:95:31
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Emitted 'error' event on DerivedLogger instance at:
    at DerivedLogger.transportEvent (/Users/eamonnmcevoy//gcloud-try-catch/node_modules/winston/lib/winston/logger.js:630:12)
    at LoggingWinston.emit (node:events:406:35)
    at onwriteError (/Users/eamonnmcevoy//gcloud-try-catch/node_modules/winston-transport/node_modules/readable-stream/lib/_stream_writable.js:449:12)
    at onwrite (/Users/eamonnmcevoy//gcloud-try-catch/node_modules/winston-transport/node_modules/readable-stream/lib/_stream_writable.js:470:11)
    at WritableState.onwrite (/Users/eamonnmcevoy//gcloud-try-catch/node_modules/winston-transport/node_modules/readable-stream/lib/_stream_writable.js:180:5)
    at /Users/eamonnmcevoy//gcloud-try-catch/node_modules/@google-cloud/promisify/build/src/index.js:114:21
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

This error cannot be caught and always crashes the app.

On node 14 (i tested 14.15.4 specifically), it behaves differently. The same error is thrown but the app will not crash.

If I include this transport do I need to be authenticated to gcloud when running locally? It should work (or at least be silent) when running locally without authentication.

**Comment by minherz** [comment]
thank you, @eamonnmcevoy for your detailed description. it seems that the documentation in README isn't descriptive. the application fails because it cannot retrieve a project id from the existing setup. given the unmanaged environment used to run the example, the code fails to identify a project id and cannot compose the logger name correctly.
we will work to fix the documentation problem.

You can define the desired project id via `LoggingOptions.projectId` parameter or as the `GOOGLE_PROJECT` environment variable in your container environment (see [public documentation](https://cloud.google.com/docs/authentication/production#automatically) for more info).

**Comment by eamonnmcevoy** [comment]
@minherz Thanks for the quick response. What should I do when running locally? 
Do I need to make sure all our developers have gcloud credentials?

It seems there is still an issue though, the package shouldn't be able to crash the application. Am I missing some error handling?

I tried wrapping the initialisation and each logging call in a try/catch but the app still crashes.

**Comment by minherz** [comment]
I would separate a question about credentials from the project id. The project id is a composite part of the log name where the log entries are written. As such, it should match the project where your environment expects to store application logs. How it is implemented depends on your DevOps and environment setups.
As I wrote, you can publish environment variable `GOOGLE_PROJECT` in the environment where the app is running with the "right" project id and the code will use it implicitly or you can read it from some config file and pass it as a parameter when you initialize your logger.

The authentication of the application or service should generally be done using a service account. If you run locally, you do it using the service account key that you [create](https://cloud.google.com/iam/docs/creating-managing-service-account-keys#creating_service_account_keys).
Generally, developers can authenticate using gcloud SDK ([`gcloud auth application-default`](https://cloud.google.com/sdk/gcloud/reference/auth/application-default)). In result the credentials will be stored in the environment variable and used implicitly. However, it should be done on the environment where you run your application and before you launch it.

**Comment by eamonnmcevoy** [comment]
We already know how to authenticate locally. Indeed I can authenticate with the service account and provide a valid projectId and everything will work. My issue is that the npm package should not cause node to crash because it can't authenticate to google cloud.

I also don't want to see developers logs in google cloud if they are developing locally, so I should be able to leave `projectId` blank and still run my app.

Thanks for your help so far!

Should I move the issue to https://github.com/googleapis/nodejs-common ? 
I suspect this is where the problem really is.

**Comment by minherz** [comment]
The libraries are intended to write logs into Google Cloud Logging service. If you use them this is what they do. If you plan to write logs locally, you should modify your logging configuration to work locally. Google client libraries do not support "local" mode of work.

**Comment by eamonnmcevoy** [comment]
I'm not asking that the package supports a 'local' mode. 
If authentication to gcloud fails, the package should not forcibly crash the application.
Is that unreasonable?

**Comment by minherz** [comment]
Do you reference to a thrown exception as a crash? Logging interfaces aren't expected to return values. For your opinion, what would be a good method to communicate an error to a caller?

The exception's source (`googleauth.js:95`) might be misleading. It happens because the project id wasn't set via LoggingOptions and the logging library calls auth to get a "default" project id. The error message clearly states the problem.

We will update the example in the README to describe the need for project id explicitly.

**Comment by eamonnmcevoy** [comment]
The exception should be logged to make the user aware, it shouldn't cause the application to crash.

Did you try my example? It's possible that I'm missing something.

The current behaviour is that if authentication to google cloud fails, then the application crashes. I can find no way to prevent this crash. Providing a projectId or not isn't really the issue, it's the behaviour when authentication fails.

I can't tell if I can authenticate to the projectId without trying to use it. If I use it and it is unable to authenticate the application will crash.

Perhaps there is an unhandled exception in the logging module? How can I prevent this crash.

![Sep-09-2021 10-00-38](https://user-images.githubusercontent.com/15125471/132647072-3b256321-be11-4868-98d9-1aebe36f4ae8.gif)

**Comment by minherz** [comment]
Thank you for the detailed explanation. I will look into it to see the crash with authentication and how we can change the error handling.
One question, just to confirm the environment that you described: is it possible from this environment to reach Google Cloud API (googleapis.com) ?

**Comment by eamonnmcevoy** [comment]
Yes I can reach googleapis.com.
Thanks, let me know if you need any other info.

**Comment by minherz** [comment]
@eamonnmcevoy i have tested your example on a local environment (in docker container) with authentication using SA private key and without configuring project id via environment variable. The exception that you described did not happened. I also got the following output printed to STDOUT:
```json
{"message":"get","level":"info"}
```

In order to reproduce it in Cloud Run, please post here the `Dockerfile` that you used to create a container that you ran.

**Comment by eamonnmcevoy** [comment]
Dockerfile
```Dockerfile
FROM node:16.4 as base
WORKDIR /app
COPY package.json package-lock.json ./

FROM base as dev
CMD npm install && node index.js
EXPOSE 3000
```

docker-compose.yml
```yml
version: "3.7"

services:
  google-try-catch:
    build:
      context: .
      target: dev
    ports:
      - 3000:3000
    container_name: google-try-catch
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: "./secrets/key.json"
    volumes:
      - node_modules:/app/node_modules/
      - .:/app

volumes:
  node_modules:
```

index.js
```js
const express = require('express')
const winston = require('winston');
const {LoggingWinston} = require('@google-cloud/logging-winston');
const app = express()
const port = 3000

const loggingWinston = new LoggingWinston({
  projectId: 'some_project_id' // a project that doesn't exist so authentication will fail
});


loggingWinston.on('error', () => console.log('error event'))
loggingWinston.on('close', () => console.log('close event'))
loggingWinston.on('drain', () => console.log('drain event'))
loggingWinston.on('finish', () => console.log('finish event'))
loggingWinston.on('pipe', () => console.log('pipe event'))
loggingWinston.on('unpipe', () => console.log('unpipe event'))

const logger = winston.createLogger({
  level: 'info',
  transports: [
    new winston.transports.Console(),
    loggingWinston,
  ],
});

app.get('/', (req, res) => {
  logger.info('get');
  res.send('Hello World!')
})

app.listen(port, () => {
  console.log(`Example app listening at http://localhost:${port}`)
})
```
output after running `curl localhost:3000`
```sh
google-try-catch    | pipe event
google-try-catch    | Example app listening at http://localhost:3000
google-try-catch    | {"message":"get","level":"info"}
google-try-catch    | unpipe event
google-try-catch    | error event
google-try-catch    | pipe event
google-try-catch    | /app/node_modules/@grpc/grpc-js/build/src/call.js:31
google-try-catch    |     return Object.assign(new Error(message), status);
google-try-catch    |                          ^
google-try-catch    | 
google-try-catch    | Error: 3 INVALID_ARGUMENT: Invalid project resource name projects/some_project_id
google-try-catch    |     at Object.callErrorFromStatus (/app/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
google-try-catch    |     at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client.js:179:52)
google-try-catch    |     at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141)
google-try-catch    |     at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)
google-try-catch    |     at /app/node_modules/@grpc/grpc-js/build/src/call-stream.js:145:78
google-try-catch    |     at processTicksAndRejections (node:internal/process/task_queues:78:11)
google-try-catch    | Emitted 'error' event on DerivedLogger instance at:
google-try-catch    |     at DerivedLogger.transportEvent (/app/node_modules/winston/lib/winston/logger.js:630:12)
google-try-catch    |     at LoggingWinston.emit (node:events:406:35)
google-try-catch    |     at onwriteError (/app/node_modules/winston-transport/node_modules/readable-stream/lib/_stream_writable.js:449:12)
google-try-catch    |     at onwrite (/app/node_modules/winston-transport/node_modules/readable-stream/lib/_stream_writable.js:470:11)
google-try-catch    |     at WritableState.onwrite (/app/node_modules/winston-transport/node_modules/readable-stream/lib/_stream_writable.js:180:5)
google-try-catch    |     at /app/node_modules/@google-cloud/promisify/build/src/index.js:114:21 {
google-try-catch    |   code: 3,
google-try-catch    |   details: 'Invalid project resource name projects/some_project_id',
google-try-catch    |   metadata: Metadata {
google-try-catch    |     internalRepr: Map(2) {
google-try-catch    |       'google.rpc.badrequest-bin' => [
google-try-catch    |         Buffer(39) [Uint8Array] [
google-try-catch    |            10,  37,  10,   4, 110,  97, 109, 101,
google-try-catch    |            18,  29,  73, 110, 118,  97, 108, 105,
google-try-catch    |           100,  32, 112, 114, 111, 106, 101,  99,
google-try-catch    |           116,  32, 114, 101, 115, 111, 117, 114,
google-try-catch    |            99, 101,  32, 110,  97, 109, 101
google-try-catch    |         ]
google-try-catch    |       ],
google-try-catch    |       'grpc-status-details-bin' => [
google-try-catch    |         Buffer(144) [Uint8Array] [
google-try-catch    |             8,   3,  18,  54,  73, 110, 118,  97, 108, 105, 100,  32,
google-try-catch    |           112, 114, 111, 106, 101,  99, 116,  32, 114, 101, 115, 111,
google-try-catch    |           117, 114,  99, 101,  32, 110,  97, 109, 101,  32, 112, 114,
google-try-catch    |           111, 106, 101,  99, 116, 115,  47, 115, 111, 109, 101,  95,
google-try-catch    |           112, 114, 111, 106, 101,  99, 116,  95, 105, 100,  26,  84,
google-try-catch    |            10,  41, 116, 121, 112, 101,  46, 103, 111, 111, 103, 108,
google-try-catch    |           101,  97, 112, 105, 115,  46,  99, 111, 109,  47, 103, 111,
google-try-catch    |           111, 103, 108, 101,  46, 114, 112,  99,  46,  66,  97, 100,
google-try-catch    |            82, 101, 113, 117,
google-try-catch    |           ... 44 more items
google-try-catch    |         ]
google-try-catch    |       ]
google-try-catch    |     },
google-try-catch    |     options: {}
google-try-catch    |   },
google-try-catch    |   note: 'Exception occurred in retry method that was not classified as transient',
google-try-catch    |   statusDetails: [
google-try-catch    |     BadRequest {
google-try-catch    |       fieldViolations: [
google-try-catch    |         FieldViolation {
google-try-catch    |           field: 'name',
google-try-catch    |           description: 'Invalid project resource name'
google-try-catch    |         }
google-try-catch    |       ]
google-try-catch    |     }
google-try-catch    |   ]
google-try-catch    | }
google-try-catch exited with code 1
```

P.S.
If I use `node:14.15` as the base image I can continue to run the app, but there are a lot of messy errors in the logs.
![image](https://user-images.githubusercontent.com/15125471/132994506-d5ebf886-9b0d-4afe-8095-40e4e0585db7.png)

**Comment by minherz** [comment]
@eamonnmcevoy thank you for putting your time to provide this information. there are few discrepancies in the provided info:
* the Dockerfile does not copy application itself
* the source file differs from one you provided in the issue description

before to continue, i would like to confirm that the reported issue is that the application that you provided crash when sending it `GET /` request in the local environment.

after testing your report, i can confirm that if you use a code with **INVALID** project id the application crashes in the local environment (i did not test its behavior in Cloud Run).
_however_, if you run this code without initializing project id (neither in the environment nor in the `LoggingWinston` constructor) the application operates as expected.

i'd like to address your claim about authentication failure as well. the authentication takes place at creation of the logger and not when the code calls it to write a log entry. the fact that you see `google-auth-library` in the callstack means only that a code from the `google-auth-library` module is called and not that the authentication process fails.

summarizing the above, the module works as expected. please, do not define invalid project id to avoid receiving an error.

the test that failed was launched using the code you provided in the [previous comment](https://github.com/googleapis/nodejs-logging-winston/issues/623#issuecomment-917663510).
the test that worked used the code in the issue description.

i had to modify Dockerfile in order to have the running container:
```dockerfile
FROM node:16.4
WORKDIR /app
COPY package.json package-lock.json index.js /app/
CMD npm install && node index.js
EXPOSE 3000
```

I ran docker using the following command to reproduce the error:
```bash
docker run -d \
--it \
--name test-623 \
--mount type=bind,source="/home/user/test_sa.key",target="/etc/test_sa.key"
--env GOOGLE_APPLICATION_CREDENTIALS="/etc/test_sa.key" \
gcr.io/minherz/test-623:invalid-project-id
```
and the similar command with the image `gcr.io/minherz/test-623:no-project-id` to have it working.

**Comment by minherz** [comment]
the tests show the designed behavior and no sign for a problem with authentication flow.

**Comment by eamonnmcevoy** [comment]
I'm surprised that the issue has been closed, please consider reopening. 

Could you comment on my suggestion here: https://github.com/googleapis/nodejs-logging-winston/issues/623#issuecomment-915863719

I should be able to catch errors from the logger and handle gracefully in my application.

Is this an unreasonable expectation?

To address your specific points:

1. > "the Dockerfile does not copy application itself"

It isn't required, if you look at the attached docker compose file the source folder is mounted into the container. You can use the commands `docker-compose build` and `docker-compose up` to run it.

Copying the files in is also fine if you are unfamiliar with this method.

2. > the source file differs from one you provided in the issue description

Yes, I added projectId and some additional logs to print events emitted from the logger. This is a minor change and demonstrates the same issues.

3.  >  if you run this code without initializing project id (neither in the environment nor in the LoggingWinston constructor) the application operates as expected.

Is the application expected to crash?

You can see from my multiple descriptions,  screen recording, and the attached output samples that this is not the case. The application crashes if projectId is missing or invalid.

4.  > if you use a code with INVALID project id the application crashes... the module works as expected.

This is obviously not reasonable behaviour from an npm package. A logging package should not crash the host application under any circumstances.

5. > i'd like to address your claim about authentication failure as well. the authentication takes place at creation of the logger and not when the code calls it to write a log entry. the fact that you see google-auth-library in the callstack means only that a code from the google-auth-library module is called and not that the authentication process fails.

It is not really my business to know the details of the authentication stack, I am trying to make a bug report about the logging package crashing the host application.

6. >  please, do not define invalid project id to avoid receiving an error.

We cannot tell if the projectId is valid before running the app, if it is invalid the app will crash. There is no way to handle the error. This is not acceptable behaviour from a logging package (or any package for that matter).

7. > the tests show the designed behavior and no sign for a problem with authentication flow.

Clearly there is a problem. You even acknowledged that if the projectId is invalid the package will crash the host app, is this the designed behaviour?

It doesn't seem reasonable to me that the package cannot handle an 'unhappy' flow. As you are no doubt aware, it should not be assumed the happy path will always occur.

Here is another error flow I didn't include in the previous post. If the SA does not have the necessary permission to log to the given project, it crashes.

![image](https://user-images.githubusercontent.com/15125471/133078574-1a8484dd-00fe-47bb-ab38-56e858b6978d.png)

**Comment by minherz** [comment]
@eamonnmcevoy I see no issue here. You continuously repeats on the same points that I feel had been addressed more than one time.

You didn't explain why you consider the crash to happened at authentication time. The authentication happens at initialization, **before** first time you log anything i.e. before a request is handled by your test application.

The crash that you describe happens when you provide **invalid** project id. This is considered as a critical error  which should not allow to continue execution. It is because if it isn't handled immediately nothing will be logged which may lead to critical problems in production. There are many workarounds that can be implemented to verify project id which aren't in the scope of the logging library.

Other remarks regarding provided files were to explain the changes that I made to Dockerfile in order to run the tests. They aren't in any form meant to be used as arguments in the discussion about this issue.

I hope that above explanation make sense. We try to follow best practices known in the industry. Still multiple opinions can differ due to specific business or operational requirements or personal experience. I'd like to point that there multiple ways to mitigate invalid configuration such as project id. Please, let us know if you need assistance to find one.

**Comment by eamonnmcevoy** [comment]
> I feel that the points you raised were addressed more than one time in this thread.

My point is that I don't want the host app to crash, so far no solution has been proposed.
If you consider an impossible to handle application crash to be the designed behaviour then so be it.

> You didn't explain why you consider the crash happening during authentication.

I consider it related to authentication because if the app can authenticate to the project then it works. If there is any issue (projectId or credentials) it crashes. I'm not sure what is confusing about that.

>  if it isn't handled immediately nothing will be logged

Winston supports multiple log transports, it should be up to the host application to decide if this scenario is critical or not.

We clearly aren't getting anywhere.  I'll look for another solution.

**Comment by minherz** [comment]
I will try to address each of your points:

> My point is that I don't want the host app to crash, so far no solution has been proposed.
> If you consider an impossible to handle application crash to be the designed behaviour then so be it.

In order to avoid the crash, please provide **valid project id** as a parameter for LoggingWinston initialization.

> I consider it related to authentication because if the app can authenticate to the project then it works. If there is any issue (projectId or credentials) it crashes.

Your interpretation of the authentication is incorrect. In Google Cloud there is no process of authentication to the project. The authentication happens vs. Google Cloud API. The project is used to compose a logger name which defines a destination where the log entries will be written to.

> Winston supports multiple log transports, it should be up to the host application to decide if this scenario is critical or not.

I accept your point that throwing an exception isn't the best method with nodejs. We will look look into replacing such code with one that emits error event where it is possible. I have opened a separate issue to track this change.

> We clearly aren't getting anywhere. I'll look for another solution.

I am really sorry that you feel disappointed. It is still confusing why you insist on using project id though.

**Comment by eamonnmcevoy** [comment]
Thank you for opening the issue
