### ISSUE TITLE
httpRequest - latency isn't working

### ISSUE THREAD

**Issue by njLT** [googleapis/nodejs-logging-winston#93]
#### Environment details

  - OS: MacOS X 10.13.5/Debian 9
  - Node.js version: 6.10.3/8.11.3
  - npm version: 3.10.10/5.6.0
  - `@google-cloud/logging-winston` version: 0.9.0

#### Steps to reproduce

  1. produce a log containing a httpRequest object which includes latency (these [docs](https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry#HttpRequest) state latency should be a number appended with an 's'. fixing the value to "3.5s" as given in the example is producing an error.
 
**Sample code:**

    let message = {
      requestMethod: "GET",
      requestUrl: "/api/getuserareas/randuser",
      status: 200,
      responseSize: "2",
      userAgent: "PostmanRuntime/7.1.5",
      remoteIp: "::1",
      latency: "3.5s"
      protocol: "HTTP/1.1"
    }

    logger.info("requested " + message.requestUrl, {
      httpRequest: message
    });
   
**Console output:** 

    info: requested /api/getuserareas/randuser requestMethod=GET, requestUrl=/api/getuserareas/randuser, status=200, responseSize=2, userAgent=PostmanRuntime/7.1.5, remoteIp=::1, latency=3.5s, protocol=HTTP/1.1

**Error:**

    undefined:50
      throw TypeError(".google.logging.type.HttpRequest.latency: object expected")
      ^

    TypeError: .google.logging.type.HttpRequest.latency: object expected
        at TypeError (native)
        at Type.HttpRequest$fromObject [as fromObject] (eval at Codegen (/Users/nishant/Documents/feild_ops_server/node_modules/@protobufjs/codegen/index.js:52:20), <anonymous>:50:9)
        at Type.LogEntry$fromObject [as fromObject] (eval at Codegen (/Users/nishant/Documents/feild_ops_server/node_modules/@protobufjs/codegen/index.js:50:33), <anonymous>:82:26)
        at Type.WriteLogEntriesRequest$fromObject [as fromObject] (eval at Codegen (/Users/nishant/Documents/feild_ops_server/node_modules/@protobufjs/codegen/index.js:50:33), <anonymous>:30:25)
        at serialize (/Users/nishant/Documents/feild_ops_server/node_modules/grpc/src/protobuf_js_6_common.js:70:23)
        at ServiceClient.Client.makeUnaryRequest (/Users/nishant/Documents/feild_ops_server/node_modules/grpc/src/client.js:544:17)
        at apply (/Users/nishant/Documents/feild_ops_server/node_modules/lodash/lodash.js:470:17)
        at ServiceClient.wrapper (/Users/nishant/Documents/feild_ops_server/node_modules/lodash/lodash.js:5329:16)
        at /Users/nishant/Documents/feild_ops_server/node_modules/@google-cloud/logging/src/v2/logging_service_v2_client.js:188:39
        at Task.timeoutFunc [as _apiCall] (/Users/nishant/Documents/feild_ops_server/node_modules/google-gax/lib/api_callable.js:171:12)
        at Task.run (/Users/nishant/Documents/feild_ops_server/node_modules/google-gax/lib/bundling.js:206:29)
        at BundleExecutor._runNow (/Users/nishant/Documents/feild_ops_server/node_modules/google-gax/lib/bundling.js:477:8)
        at Timeout._onTimeout (/Users/nishant/Documents/feild_ops_server/node_modules/google-gax/lib/bundling.js:416:12)
        at ontimeout (timers.js:386:14)
        at tryOnTimeout (timers.js:250:5)
        at Timer.listOnTimeout (timers.js:214:5)

Is the latency value supposed to be something else? I did try making it numeric (removing the 's'), which didn't work either. No error is produced if  the latency field is removed.

**Comment by ofrobots** [comment]
Apologies for the wrong doc link. That goes to the JSON/REST version of the Stackdriver Logging api, while this library uses the gRPC / Protobuf transport.

Here's the [correct link](https://cloud.google.com/logging/docs/reference/v2/rpc/google.logging.type#google.logging.type.HttpRequest) to the LogEntry documentation. Note that the `latency` field needs to be a [`Duration`](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#google.protobuf.Duration) object with `seconds` and `nanos` fields.
